services:
#  pg:
#    image: postgres
#    expose:
#      - 5432
#    environment:
#      POSTGRES_USER: "${POSTGRES_USER}"
#      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
#      POSTGRES_DB: "${POSTGRES_DB}"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
#      interval: 5s
#      timeout: 3s
#      retries: 6
#
#  redis:
#    image: redis
#    expose:
#      - 6379


  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: bash -c "
      uv run python manage.py migrate
      && uv run gunicorn config.wsgi -b 0.0.0.0:8080
      "
#    depends_on:
#      pg:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
