services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 6

  redis:
    image: redis
    ports:
      - 6379:6379


  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: bash -c "uv run python manage.py migrate &&        
        uv run gunicorn config.wsgi -b 0.0.0.0:8080 &&
        uv run celery -A config worker --concurrency 1 -E &&
        uv run celery -A config beat -l INFO"
    depends_on:
      pg:
        condition: service_healthy

volumes:
  postgresdata: