[project]
name = "djangoproject"
version = "0.1.0"
description = ""
authors = [
    {name = "Alexandr",email = "gorbenich@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "environs>=14.2.0",
    "pillow>=11.2.1",
    "yookassa>=3.5.0",
]
