# Generated by Django 5.2 on 2025-06-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина покупок",
                "verbose_name_plural": "Корзины покупок",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция корзины",
                "verbose_name_plural": "Позиции корзины",
            },
        ),
    ]
